# Generated by Django 6.1 on 2026-09-21 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_inscripcionclase_clase_clientes_perfilcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='membresia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='gimnasio.cliente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gimnasio.cliente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='gimnasio.membresia'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('asistio', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gimnasio.inscripcionclase')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionFisica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gimnasio.cliente')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to='gimnasio.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gimnasio.clase')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_meta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='gimnasio.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='gimnasio.cliente')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_creadas', to='gimnasio.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.PositiveIntegerField(default=10)),
                ('descanso_segundos', models.PositiveIntegerField(default=60)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_ejercicios', to='gimnasio.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_ejercicios', to='gimnasio.rutina')),
            ],
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(related_name='rutinas', through='gimnasio.RutinaEjercicio', to='gimnasio.ejercicio'),
        ),
        migrations.AddField(
            model_name='clase',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='gimnasio.sala'),
        ),
    ]
